	            <!--</div>
	        </div>-->
	    </div>
	</div>
	<!--<div class="container">
		<div class="row">
			<div class="col-md-4 col-md-offset-4 text-center">
				HXPHP <?php echo date("Y"); ?> &copy; - Todos os direitos reservados
			</div>
		</div>
	</div>-->


	<!-- ==============================================
	   Créditos (Credits)
	=============================================== --> 
	<section class="copyright">
	  <div class="container">
	    <div class="col-md-12">
	      <div class="text-center"> 
	        <!-- Logo Header -->
	        <section id="fox_footer" class="fox_footer">
	          <div> <img src="<?php echo IMG; ?>logofooter.png" alt="Foxin by Elisandro Mello">  - &copy;<?php echo date("Y")  ?> - Design and Development Encoded by <i class="fa fa-cloud-upload"></i> Elisandro Mello</div>
	          
	        </section>
	        <!--/ Logo Header-->
	      </div>
	    </div>
	  </div>
	</section>



	<script src="<?php echo BOWER; ?>bootstrap/dist/js/bootstrap.min.js"></script>
</body>
</html>